import { Router } from "express";
import { getOnboardingHanlder, onboardingHandler, onboardingPersonalHandler, onboardingEducationHandler, onboardingExperienceHandler, onboardingSkillsCertsHandler, onboardingResumeHandler, } from "../../controller/candidate/onboardingController.js";
import { authenticate } from "../../middleware/authMiddleware.js";
import { validate } from "../../middleware/validationMiddleware.js";
import { onboardingSchema, personalInfoSchema, educationStepSchema, experienceStepSchema, skillsCertsStepSchema, resumeStepSchema, } from "../../validation/onboardingValidation.js";
const router = Router();
router.get("/", authenticate, getOnboardingHanlder);
router.post("/", authenticate, validate(onboardingSchema), onboardingHandler);
router.post("/personal", authenticate, validate(personalInfoSchema), onboardingPersonalHandler);
router.post("/education", authenticate, validate(educationStepSchema), onboardingEducationHandler);
router.post("/experience", authenticate, validate(experienceStepSchema), onboardingExperienceHandler);
router.post("/skills-certs", authenticate, validate(skillsCertsStepSchema), onboardingSkillsCertsHandler);
router.post("/resume", authenticate, validate(resumeStepSchema), onboardingResumeHandler);
export default router;
